#!/bin/bash
set -e
npm i -q --only=prod --ignore-scripts --global-style @venzee/deployment-tools

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
feature_id=`${DIR}/extractfeatureid`

node node_modules/@venzee/deployment-tools/lib/createCustomConfig

cp node_modules/@venzee/deployment-tools/tools/clearcdncache /home/$PROJECT_PATH/app/clearcdncache
cp node_modules/@venzee/deployment-tools/tools/extractfeatureid  /home/$PROJECT_PATH/app/extractfeatureid 
cp node_modules/@venzee/deployment-tools/tools/deployfeature.sh  /home/$PROJECT_PATH/app/deployfeature.sh
